### ISSUE TITLE
[FEAT] - Use Thymeleaf fragments for the html views

### ISSUE THREAD

**Issue by arungalva** [arungalva/4th-year-Project-Website#36]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated that I need to include the same header, nav and footer to any new html page I create

**Describe the solution you'd like**
We should use [thymeleaf fragments](https://www.thymeleaf.org/doc/articles/layouts.html) to split up an html file into header, footer and nav fragments. 

**Acceptance criteria**
I should be able to create a new html file and use the fragements to include header, footer and navigation in my new file

**Additional context**

- [x] Create header fragment 
- [x] Create footer fragment
- [ ] Create nav fragment

**Comment by ShasRanasinghe** [comment]
completed in #45
