### ISSUE TITLE
[FEAT] Set up the MySql database on Heroku

### ISSUE THREAD

**Issue by seanrt** [arungalva/4th-year-Project-Website#37]
**Is your feature request related to a problem? Please describe.**
We need to have a database deployed on Heroku so that our production application can persist data

**Describe the solution you'd like**
Our system is using MySql, so we need to set up a MySql DB on the Heroku machine. This DB instance needs to have the correct databases and users for our project. The user we will use will be called "eggplant" and its password will be "emoji".

**Acceptance criteria**
We will know that the database is deployed if we can store data in the tables, restart the machine, query the tables, and see that the data persisted. This is essential for persisting our data when the Heroku app is shut down.

**Comment by arungalva** [comment]
The setup is complete. The connection string for the database is 
```
mysql://b208ab0380c202:69254c69@us-cdbr-iron-east-03.cleardb.net/heroku_29bdee14ebe81e6?reconnect=true
```
