### ISSUE TITLE
[BUG] - Projects have 1 student added by default

### ISSUE THREAD

**Issue by seanrt** [arungalva/4th-year-Project-Website#53]
**Describe the bug**
Currently, when a new project is added by a professor, the project has 1 dummy student added to its 'students' column. The project should start with no students.

**To Reproduce**
1. Go to 'https://eggplant-emoji.herokuapp.com/addproject'
2. Add a new project

**Expected behavior**
The new project should be added, but there should be no student by default

**Actual behavior**
The new project has a default dummy student

**Screenshots**
![image](https://user-images.githubusercontent.com/12137866/53889225-0af66200-3ff4-11e9-8e98-973482023c90.png)

**Comment by ShasRanasinghe** [comment]
Fixed in #67
