### ISSUE TITLE
[BUG] - Make 'Engineering Project' button in the header not clickable

### ISSUE THREAD

**Issue by blessingomotayo** [arungalva/4th-year-Project-Website#54]
**Describe the bug**
The Nav bar 'Engineering Project' is clickable but it shouldn't be.

**To Reproduce**
1. Go to '/'
2. Click on 'Engineering Project' in the navigation bar
3. Observe that it does nothing.

**Expected behavior**
Shouldn't be able to click on it
**Actual behavior**
It is clickable
**Screenshots**

**Additional context**

**Comment by arungalva** [comment]
Instead of making this non-clickable, shouldn't we just link it to the home page?
