### ISSUE TITLE
Move Database to Postgres

### ISSUE THREAD

**Issue by arungalva** [arungalva/4th-year-Project-Website#56]
**Is your feature request related to a problem? Please describe.**
Heroku has first class support for Postgres. We have been running into many issues with mysql mentioned at #47 

**Describe the solution you'd like**
We would have to add Postgres add on to the Heroku app. Also need to add Postgres JDBC connector as a dependency to connect to the postgres db. This would also entail installing Postgres on travis so that we can run the tests correctly

**Acceptance criteria**
Go to Heroku, add a new project and refresh the app to see if the new project got persisted

**Additional context**

**Comment by arungalva** [comment]
Running into a few issues atm so I am going to change it to sqlite for now

**Comment by seanrt** [comment]
This issue should be closed right? @arungalva
