### ISSUE TITLE
[BUG] - Header and footer fragments adding error

### ISSUE THREAD

**Issue by ShasRanasinghe** [arungalva/4th-year-Project-Website#59]
**Describe the bug**
The div that adds the header and footer fragments show an error due to the double colon

**To Reproduce**
1. Open any of the html files that have the fragments added to it
2. Look at the error displayed for the double colon

**Expected behavior**
There shouldn't be an error when trying to load the fragments

**Actual behavior**
This bug is not breaking anything but there is an error and it needs to handled

**Comment by blessingomotayo** [comment]
Issue has been fixed elsewhere. Closing issue.
