### ISSUE TITLE
Let users sign up as students or Professors

### ISSUE THREAD

**Issue by arungalva** [arungalva/4th-year-Project-Website#65]
**Is your feature request related to a problem? Please describe.**
Professors and students have different permissions and access. Currently there is no way to differentiate between the two types of users

**Describe the solution you'd like**
Letting users sign up as professor and student allows us to differentiate the functionality between the two types of users

**Acceptance criteria**
I should be able to sign up as a professor and taken to the professor page and sign up as students and taken to the /projects page

**Additional context**

**Comment by seanrt** [comment]
This issue should be closed right? The current sign up feature allows users to sign up as the appropriate role. That being said, the student log in should redirect to the students page.

**Comment by blessingomotayo** [comment]
this should be closed, yeah

**Comment by ShasRanasinghe** [comment]
Issue closed in #87
