### ISSUE TITLE
[BUG] - CSS not loading when running the app locally

### ISSUE THREAD

**Issue by seanrt** [arungalva/4th-year-Project-Website#71]
**Describe the bug**
I cloned the repository on my desktop. Running the app from AppApplication.java worked, but not of the static assets including CSS would load.

**To Reproduce**
1. Clone this project repo
2. Run the app from AppApplication.java
3. Load any of the app pages (e.g. localhost:8080)

**Expected behavior**
The CSS and static assets should load.

**Actual behavior**
None of the assets or CSS load.

**Screenshots**
Here's how the page looks initially:
![image](https://user-images.githubusercontent.com/12137866/54648810-044cfd80-4a7e-11e9-8562-cf1e65ec2bcf.png)

Here's how the page should look:
![image](https://user-images.githubusercontent.com/12137866/54648857-32cad880-4a7e-11e9-9de5-c06808065d58.png)

**Comment by arungalva** [comment]
I followed the steps you mentioned and everything worked fine for me. here is the screen I see
![image](https://user-images.githubusercontent.com/12630802/54649180-930e4a00-4a7f-11e9-945a-bf4d6a75e846.png)
