### ISSUE TITLE
[BUG] - The professor view has a hard-coded program restriction for all projects

### ISSUE THREAD

**Issue by seanrt** [arungalva/4th-year-Project-Website#82]
**Describe the bug**
The professor view shows the list of unarchived projects. The projects all show the same program restriction (which is hard-coded). The program restrictions should be read from the project entity.

**To Reproduce**
1. Go to /professor
2. Add a new project with your own program restrictions selected
3. Submit the add project to return to the professor view. The program restrictions for your new project will be incorrect.

**Expected behavior**
The professor view should show the actual program restrictions for the project

**Actual behavior**
Every project shows the program restrictions as SE

**Screenshots**
![image](https://user-images.githubusercontent.com/12137866/54685739-efa84e00-4aed-11e9-99cf-aab91a7b0dd5.png)

**Additional context**
This is related to #74

**Comment by ShasRanasinghe** [comment]
Issue fixed in #95
